services:
  smtp-server:
    image: elttwl/smtp-server:latest
    container_name: elttwl-smtp-server
    ports:
      - "25:25"
    env_file:
      - .env
    restart: always
    labels:
      - "maintainer=elttwl <elttwl@qq.com>"
